# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: text_speech.proto
# Protobuf Python Version: 5.27.2
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    5,
    27,
    2,
    '',
    'text_speech.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x11text_speech.proto\x12\x0btext_speech\"\x14\n\x04Text\x12\x0c\n\x04text\x18\x01 \x01(\t\"\x17\n\x06Speech\x12\r\n\x05\x41udio\x18\x01 \x01(\x0c\x32=\n\nTextSpeech\x12/\n\x03Say\x12\x11.text_speech.Text\x1a\x13.text_speech.Speech\"\x00\x62\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'text_speech_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  DESCRIPTOR._loaded_options = None
  _globals['_TEXT']._serialized_start=34
  _globals['_TEXT']._serialized_end=54
  _globals['_SPEECH']._serialized_start=56
  _globals['_SPEECH']._serialized_end=79
  _globals['_TEXTSPEECH']._serialized_start=81
  _globals['_TEXTSPEECH']._serialized_end=142
# @@protoc_insertion_point(module_scope)
